export const courses = [
    // Package Courses
    {
      id: 37,
      title: 'Primary Classes Full Package (Class 1-5)',
      category: 'Full Package',
      instructor: 'Multiple Expert Teachers',
      rating: 4.9,
      students: 120,
      price: 11999,
      description: 'Complete coverage of all subjects for Classes 1-5. Includes Mathematics, English, and EVS/Science with comprehensive study materials and assessments.',
      level: 'Primary Package'
    },
    {
      id: 38,
      title: 'Secondary Classes Full Package (Class 6-10)',
      category: 'Full Package',
      instructor: 'Multiple Expert Teachers',
      rating: 4.9,
      students: 150,
      price: 19999,
      description: 'Comprehensive package covering all subjects for Classes 6-10. Includes Mathematics, Science, and English with exam preparation and practice tests.',
      level: 'Secondary Package'
    },
    {
      id: 39,
      title: 'Class 11 Complete Package',
      category: 'Full Package',
      instructor: 'Multiple Expert Teachers',
      rating: 4.9,
      students: 85,
      price: 13999,
      description: 'Complete package for Class 11 covering Physics, Chemistry, and Mathematics with practical training and competitive exam preparation.',
      level: 'Senior Secondary Package'
    },
    {
      id: 40,
      title: 'Class 12 Complete Package',
      category: 'Full Package',
      instructor: 'Multiple Expert Teachers',
      rating: 4.9,
      students: 90,
      price: 14999,
      description: 'Comprehensive package for Class 12 covering Physics, Chemistry, and Mathematics with board exam preparation and practice tests.',
      level: 'Senior Secondary Package'
    },
    // Individual Courses
    {
      id: 1,
      title: 'Mathematics (Class 1)',
      category: 'Class 1',
      instructor: 'Mrs. Sharma',
      rating: 4.8,
      students: 45,
      price: 1999,
      description: 'Foundation mathematics covering numbers, basic addition, subtraction, and shapes.',
      level: 'Primary'
    },
    // ... [Previous individual courses remain the same, continuing from id 1 to 36]
    {
      id: 2,
      title: 'English (Class 1)',
      category: 'Class 1',
      instructor: 'Ms. Roberts',
      rating: 4.9,
      students: 42,
      price: 1999,
      description: 'Basic English covering alphabets, phonics, simple words, and reading.',
      level: 'Primary'
    },
    {
      id: 3,
      title: 'EVS (Class 1)',
      category: 'Class 1',
      instructor: 'Mrs. Gupta',
      rating: 4.7,
      students: 38,
      price: 1999,
      description: 'Environmental Studies covering basic concepts about nature, family, and surroundings.',
      level: 'Primary'
    },
    {
      id: 4,
      title: 'Mathematics (Class 2)',
      category: 'Class 2',
      instructor: 'Mr. Verma',
      rating: 4.8,
      students: 52,
      price: 2199,
      description: 'Advanced arithmetic, multiplication tables, and basic geometry.',
      level: 'Primary'
    },
    {
      id: 5,
      title: 'English (Class 2)',
      category: 'Class 2',
      instructor: 'Mrs. Thompson',
      rating: 4.7,
      students: 48,
      price: 2199,
      description: 'Grammar basics, sentence formation, and story reading.',
      level: 'Primary'
    },
    {
      id: 6,
      title: 'EVS (Class 2)',
      category: 'Class 2',
      instructor: 'Mr. Kumar',
      rating: 4.8,
      students: 45,
      price: 2199,
      description: 'Learning about plants, animals, and basic science concepts.',
      level: 'Primary'
    },
    {
      id: 7,
      title: 'Mathematics (Class 3)',
      category: 'Class 3',
      instructor: 'Mrs. Reddy',
      rating: 4.8,
      students: 55,
      price: 2399,
      description: 'Fractions, decimals, measurements, and mental math techniques.',
      level: 'Primary'
    },
    {
      id: 8,
      title: 'English (Class 3)',
      category: 'Class 3',
      instructor: 'Mr. Wilson',
      rating: 4.7,
      students: 50,
      price: 2399,
      description: 'Creative writing, comprehension, and advanced grammar.',
      level: 'Primary'
    },
    {
      id: 9,
      title: 'Science (Class 3)',
      category: 'Class 3',
      instructor: 'Mrs. Patel',
      rating: 4.8,
      students: 48,
      price: 2399,
      description: 'Basic scientific concepts, experiments, and environmental awareness.',
      level: 'Primary'
    },
    {
      id: 10,
      title: 'Mathematics (Class 4)',
      category: 'Class 4',
      instructor: 'Mr. Sharma',
      rating: 4.9,
      students: 58,
      price: 2599,
      description: 'Advanced arithmetic, basic algebra, and geometric concepts.',
      level: 'Primary'
    },
    {
      id: 11,
      title: 'English (Class 4)',
      category: 'Class 4',
      instructor: 'Mrs. Anderson',
      rating: 4.8,
      students: 52,
      price: 2599,
      description: 'Advanced reading, writing skills, and literature appreciation.',
      level: 'Primary'
    },
    {
      id: 12,
      title: 'Science (Class 4)',
      category: 'Class 4',
      instructor: 'Dr. Gupta',
      rating: 4.7,
      students: 50,
      price: 2599,
      description: 'Natural phenomena, basic physics concepts, and life sciences.',
      level: 'Primary'
    },
    {
      id: 13,
      title: 'Mathematics (Class 5)',
      category: 'Class 5',
      instructor: 'Dr. Rao',
      rating: 4.9,
      students: 62,
      price: 2799,
      description: 'Complex arithmetic, introduction to algebra, and advanced geometry.',
      level: 'Primary'
    },
    {
      id: 14,
      title: 'English (Class 5)',
      category: 'Class 5',
      instructor: 'Ms. Williams',
      rating: 4.8,
      students: 55,
      price: 2799,
      description: 'Advanced grammar, creative writing, and public speaking.',
      level: 'Primary'
    },
    {
      id: 15,
      title: 'Science (Class 5)',
      category: 'Class 5',
      instructor: 'Mr. Kumar',
      rating: 4.8,
      students: 58,
      price: 2799,
      description: 'Advanced scientific concepts, experiments, and environmental science.',
      level: 'Primary'
    },
    {
      id: 16,
      title: 'Mathematics (Class 6)',
      category: 'Class 6',
      instructor: 'Dr. Kapoor',
      rating: 4.9,
      students: 65,
      price: 3499,
      description: 'Introduction to algebra, geometry, and advanced arithmetic.',
      level: 'Secondary'
    },
    {
      id: 17,
      title: 'Science (Class 6)',
      category: 'Class 6',
      instructor: 'Mrs. Sinha',
      rating: 4.8,
      students: 58,
      price: 3499,
      description: 'Basic concepts in physics, chemistry, and biology.',
      level: 'Secondary'
    },
    {
      id: 18,
      title: 'English (Class 6)',
      category: 'Class 6',
      instructor: 'Mrs. Brown',
      rating: 4.7,
      students: 55,
      price: 3499,
      description: 'Literature appreciation, advanced grammar, and creative writing.',
      level: 'Secondary'
    },
    {
      id: 19,
      title: 'Mathematics (Class 7)',
      category: 'Class 7',
      instructor: 'Dr. Sharma',
      rating: 4.8,
      students: 60,
      price: 3699,
      description: 'Advanced algebra, geometry, and mathematical reasoning.',
      level: 'Secondary'
    },
    {
      id: 20,
      title: 'Science (Class 7)',
      category: 'Class 7',
      instructor: 'Mrs. Verma',
      rating: 4.7,
      students: 55,
      price: 3699,
      description: 'Advanced concepts in physics, chemistry, and biology.',
      level: 'Secondary'
    },
    {
      id: 21,
      title: 'English (Class 7)',
      category: 'Class 7',
      instructor: 'Mr. Thompson',
      rating: 4.8,
      students: 52,
      price: 3699,
      description: 'Advanced literature, writing skills, and communication.',
      level: 'Secondary'
    },
    {
      id: 22,
      title: 'Mathematics (Class 8)',
      category: 'Class 8',
      instructor: 'Dr. Kumar',
      rating: 4.9,
      students: 58,
      price: 3899,
      description: 'Complex algebra, geometry, and introduction to trigonometry.',
      level: 'Secondary'
    },
    {
      id: 23,
      title: 'Science (Class 8)',
      category: 'Class 8',
      instructor: 'Dr. Gupta',
      rating: 4.8,
      students: 54,
      price: 3899,
      description: 'Comprehensive science with focus on practical applications.',
      level: 'Secondary'
    },
    {
      id: 24,
      title: 'English (Class 8)',
      category: 'Class 8',
      instructor: 'Mrs. Wilson',
      rating: 4.7,
      students: 50,
      price: 3899,
      description: 'Advanced grammar, literature analysis, and writing skills.',
      level: 'Secondary'
    },
    {
      id: 25,
      title: 'Mathematics (Class 9)',
      category: 'Class 9',
      instructor: 'Dr. Reddy',
      rating: 4.9,
      students: 45,
      price: 4299,
      description: 'Advanced algebra, coordinate geometry, and trigonometry.',
      level: 'Secondary'
    },
    {
      id: 26,
      title: 'Science (Class 9)',
      category: 'Class 9',
      instructor: 'Dr. Sharma',
      rating: 4.8,
      students: 42,
      price: 4299,
      description: 'Physics, chemistry, and biology with practical experiments.',
      level: 'Secondary'
    },
    {
      id: 27,
      title: 'English (Class 9)',
      category: 'Class 9',
      instructor: 'Ms. Roberts',
      rating: 4.7,
      students: 40,
      price: 4299,
      description: 'Literature, advanced writing, and exam preparation.',
      level: 'Secondary'
    },
    {
      id: 28,
      title: 'Mathematics (Class 10)',
      category: 'Class 10',
      instructor: 'Dr. Verma',
      rating: 4.9,
      students: 48,
      price: 4499,
      description: 'Complete mathematics preparation for board exams.',
      level: 'Secondary'
    },
    {
      id: 29,
      title: 'Science (Class 10)',
      category: 'Class 10',
      instructor: 'Dr. Patel',
      rating: 4.8,
      students: 45,
      price: 4499,
      description: 'Comprehensive science preparation for board exams.',
      level: 'Secondary'
    },
    {
      id: 30,
      title: 'English (Class 10)',
      category: 'Class 10',
      instructor: 'Mrs. Thompson',
      rating: 4.8,
      students: 42,
      price: 4499,
      description: 'Complete English preparation for board exams.',
      level: 'Secondary'
    },
    {
      id: 31,
      title: 'Physics (Class 11)',
      category: 'Class 11',
      instructor: 'Dr. Mathur',
      rating: 4.9,
      students: 42,
      price: 4999,
      description: 'Mechanics, thermodynamics, and waves with practical applications.',
      level: 'Senior Secondary'
    },
    {
      id: 32,
      title: 'Chemistry (Class 11)',
      category: 'Class 11',
      instructor: 'Dr. Singh',
      rating: 4.8,
      students: 38,
      price: 4999,
      description: 'Organic chemistry, inorganic chemistry, and physical chemistry fundamentals.',
      level: 'Senior Secondary'
    },
    {
      id: 33,
      title: 'Mathematics (Class 11)',
      category: 'Class 11',
      instructor: 'Dr. Rao',
      rating: 4.9,
      students: 35,
      price: 4999,
      description: 'Advanced calculus, algebra, and coordinate geometry.',
      level: 'Senior Secondary'
    },
    {
      id: 34,
      title: 'Physics (Class 12)',
      category: 'Class 12',
      instructor: 'Dr. Kumar',
      rating: 4.9,
      students: 35,
      price: 5499,
      description: 'Advanced physics covering electromagnetism, modern physics, and optics.',
      level: 'Senior Secondary'
    },
    {
      id: 35,
      title: 'Chemistry (Class 12)',
      category: 'Class 12',
      instructor: 'Dr. Gupta',
      rating: 4.8,
      students: 32,
      price: 5499,
      description: 'Advanced organic, inorganic, and physical chemistry.',
      level: 'Senior Secondary'
    },
    {
      id: 36,
      title: 'Mathematics (Class 12)',
      category: 'Class 12',
      instructor: 'Dr. Verma',
      rating: 4.8,
      students: 40,
      price: 5499,
      description: 'Calculus, vectors, 3D geometry, and probability for board exams.',
      level: 'Senior Secondary'
    }
  ];
